language: python
python:
- '2.7'
install:
- pip install -U setuptools
script: true
after_success: python build.py --command="sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: XmrF+/vNo7rs8tVabYRwF9P2RW3tkJxJJiCqK0NCHhS03rb5Tll2gxlIDnNJcoENoX8ggG4qhue8oExUsrGwG06v38LNnMTzfSQmRmqnev2g3WZQXRjb6YsHfGYmUYCwRUN6ZLkAhTAX6Lls5rRMCKzTu7mUGJ+t8ohWyM8xlecNWfQRdv/wsZYI665qOzQ60GSIp3zV7ibez4HYJ71ODDTDvv64qnwr3QC9rhTneQeDB2QH/rK3/Jx+jqZwVj3vaoyWMpjcCebLBYP8W1i0neDG2HzWdFDRZ3CRjXA7ZoGkKBPFsRuLzsd3TJt7vUnrNjrBbvDKzEjhCQ3bJVsEojNzqYb/CCUJu5kiB4t6/Kec+VqTq8WafORqMAaDRMzhWqqCZC3otqw3/J2tt4HFFFL/ar1FBsijt0Pbc+gxUk5nJP6FoKPmqivtKpEzVIDK9/LyJt9V9A+qb/eedomeUMZ0PYayOA1sfHYvWnMPcVjv3zB1FvoesGMqFpx8QEOJAnr2OoToKi3RDjApUFt9h9xuslcM0DiH8bzFBoxOK70NuWD93OB23ssXOocnwu218KgQLWDmM2jXv1VwI2KhBKVouzbgURmlSQXUdhQiT9dX9d1KqaOw3aM4TRh90YhrPnySN8tqq5t99zvU2XYmjv0wR6FHbLqZdGKrfGjGIOI=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-anidb-tvdb*"
  - "dist/oem_database_anidb_tvdb*"
  on:
    repo: KingJ/oem-database-anidb-tvdb
    tags: true
