language: python
python:
- '2.7'
install:
- pip install -U setuptools
script: true
after_success: python build.py --command="sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: OAXIZjzJV9DwWKwMZcUO4nKvUKNSlKAOdoYlG3cLtWmOeNX6ZU52eeSk/3ya2UA2Xf94BZkRF/6QLznvfnycFRXCVJ3XLrorZE51yya36hwFy2SNm3ubsLoJCsx1hJhnsEM/vCNZj+hXmYPoLFQjwRBho3Lz1wlmagmIYr3XnsoIZ8Mlzbwla4ZD9aotpDpac4AC/gvXwpy3gknSN7dWozMEKm6cGGCdeqaY6tArvVIW5fHlZkNJEQNzJu7MQNxffoz0hu90bt/UPlqWQM0rhZr3CegifZTQQzyVgImHsV5Pde4K3dDbS/zGUU7TriFpTm0uf3kYmBCc6yjgtL8EWMyKY8KurYPkAWgvkHEMVQrt3xJwect8YfumxFEUabj02un+fVnBVf8UdnzkQrgMAAdrjZpPbJZWtllThuYTbPMTemnYa2PfLqMS34DG3yAH7Jzc5rLpM+j9dFz0Zqk9RfKllzT0GTUqp2KLUM0RzDnuAlAxHcaBGRCV456h/dv6yrew5h2j9IIbjTTaWNWS1pCUWS/r7nRzj1xHhRou8Sub8OvFTJ/yl4ki6bcbM7ePYm/kvqyR1b8Eb47pdqmkMqBp18m26ityTmgYP6jLRrUka+0/LNZfQ6sDQpcxXYe21bK+tXa0cgjNJiC8ecY+doewpKjoqNIRutNIiFGjYfY=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-anidb-tvdb*"
  - "dist/oem_database_anidb_tvdb*"
  on:
    repo: KingJ/oem-database-anidb-tvdb
    tags: true
