language: python
python:
- '2.7'
install:
- pip install -U setuptools
script: true
after_success: python build.py --command="sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: dg1h5Y0YXgy6y9TuwrtcVgjwnB+ioFc7Ip6/QIaNxxg7MQxdNXEwSbDpyC/mPSSfrfN3YeOELs2LHYvbOabx+Z6oOa8c2WZ3qdxxhbs3k3zJ8mwB8nw441Tvmtz53h/YfiG8uPX1OxGJy4rMLo3/2bxlxGQ1wUUa4/1dSet35tIBsawB/aaiQlenirYiRqgKkrBvtZaKTry4BKkLvlhEGRo/SavlEMO84KMv5QysKQ5WCqNjtAcfJK4OX3zfyBoYZaVmfgHpP8KadwYd2BaEdBfi7FwEhBl2Vw+slNge5XGuGMbvSc7unHly5U/5Q3PAN1NxC1Mf4fc66evCd9G0p2SBmCp5NFi50lJBGs3ypwhLSbqm8gmU2i0qd4h34tYhQ99DDcmpgH50qatJrsT6/Geyr97nCaYILYZ8H++yHdiPaf5LgKFr6mygz0N5oVgdSgPWA9lYdlByoW1I/oQpHt/AhXa+34DcduEoY6aCxgogrr8T/QcpqzAk4oL5ToZwmhJLYbz2bLEZzqWXE1Uk/idTlRvdHsYz0us8KvlSmzB83pLmGpfusEExQ7PvEK+HjcdewmrNBtB2tX43taZeK2GLi1TZTCuQmqZH36Qkn/BuEMvFiYKo3BDT/vOjRFiYoI093PaKL75epH+KS2Ju2awDRrKYnidu5jf7EScbBV8=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-anidb-tvdb*"
  - "dist/oem_database_anidb_tvdb*"
  on:
    repo: KingJ/oem-database-anidb-tvdb
    tags: true
